// Course codes constant

const COURSE_CODES = Object.freeze({
  CS305: "DESIGN AND ANALYSIS ALGORITHMS",
  CS307: "DATABASE SYSTEMS I",
  CS302: "COMPUTER ARCHITECTURE",
  CS303: "SOFTWARE ENGINEERING",
  CS306: "OPERATING SYSTEMS",
  CS304: "COMPUTER GRAPHICS",
});

module.exports = COURSE_CODES;
